// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJlxkQZEzHTcoG6MY72iQZMwFmr8PAOh0',
    appId: '1:973854880042:web:25ab105da3520c7c34ee53',
    messagingSenderId: '973854880042',
    projectId: 'home-care-9a355',
    authDomain: 'home-care-9a355.firebaseapp.com',
    storageBucket: 'home-care-9a355.firebasestorage.app',
    measurementId: 'G-ZFQTWYRKK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOMdMoXQRd5QWvqEdiaj0cn60AwXM-R38',
    appId: '1:973854880042:android:6b51524179634ad034ee53',
    messagingSenderId: '973854880042',
    projectId: 'home-care-9a355',
    storageBucket: 'home-care-9a355.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQCdWfv7BLpwAcHYrVXd3hjgWf7Oqq_d8',
    appId: '1:973854880042:ios:05685bd4969e798534ee53',
    messagingSenderId: '973854880042',
    projectId: 'home-care-9a355',
    storageBucket: 'home-care-9a355.firebasestorage.app',
    iosBundleId: 'com.example.homeCareSimulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQCdWfv7BLpwAcHYrVXd3hjgWf7Oqq_d8',
    appId: '1:973854880042:ios:05685bd4969e798534ee53',
    messagingSenderId: '973854880042',
    projectId: 'home-care-9a355',
    storageBucket: 'home-care-9a355.firebasestorage.app',
    iosBundleId: 'com.example.homeCareSimulator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJlxkQZEzHTcoG6MY72iQZMwFmr8PAOh0',
    appId: '1:973854880042:web:73621ca271df4bbe34ee53',
    messagingSenderId: '973854880042',
    projectId: 'home-care-9a355',
    authDomain: 'home-care-9a355.firebaseapp.com',
    storageBucket: 'home-care-9a355.firebasestorage.app',
    measurementId: 'G-08PD5HEP01',
  );
}
